-- S1 batch (ids 406, 407, 408)
UPDATE questions SET explanation = CASE id
WHEN 406 THEN 'O paradoxo consiste em uma contradição aparente que revela uma verdade profunda: a doença que destrói a memória também apaga a consciência de estar doente, criando um ciclo de esquecimento sobre o próprio esquecimento.

A alternativa A é correta porque o trecho articula exatamente essa crueldade paradoxal — ao esquecer que tem ''a doença do esquecimento'', Eunice vivencia momentos de bem-estar ilusório, o que intensifica a dimensão trágica do Alzheimer. B é incorreta porque o texto não descreve simulação, mas esquecimento genuíno da condição. C é incorreta porque o trecho não aborda tratamentos médicos. D é incorreta porque Eunice não está recusando o diagnóstico de forma consciente — ela simplesmente se esquece dele.'
WHEN 407 THEN 'A alternativa B é correta porque a longa enumeração sensorial — maresia, cheiro de mangue, som do mar, formato das ilhas, mate com limão, areia nos pés — demonstra que os vínculos afetivos de Eunice com o Rio permanecem intactos apesar de tudo o que sofreu ali, incluindo a prisão e o desaparecimento do marido. A frase ''Sou a mesma, e outra'' explicita que ela reconhece as rupturas biográficas sem que estas anulem a ligação com o lugar. A é incorreta porque Eunice admite a transformação ao dizer ''e outra'', não a nega. C é incorreta porque não há idealização — ela descreve elementos concretos e reais da cidade. D é incorreta porque a decisão não é superficial, mas fundamentada numa reconexão profunda com a própria história.'
WHEN 408 THEN 'A intertextualidade temática consiste na ressonância entre motivos distintos dentro de uma mesma obra, de modo que um tema ilumina outro por analogia ou espelhamento.

A alternativa C é correta porque a afirmação médica sobre a irreversibilidade do Alzheimer ecoa tematicamente a irreversibilidade do desaparecimento político de Rubens Paiva — em ambos os casos, a perda é definitiva e não há recuperação possível, conectando a perda da memória individual à perda da memória coletiva e da identidade nacional sob a ditadura. A é incorreta porque, embora haja paralelo com o desaparecimento, a alternativa omite a dimensão da identidade nacional que o enunciado exige. B é incorreta porque o texto não faz crítica a investimentos em pesquisa. D é incorreta porque o narrador não se mostra resignado, mas revoltado, como evidenciam suas perguntas retóricas anteriores.'
END
WHERE id IN (406, 407, 408);

-- S2 batch (ids 409, 410, 411)
UPDATE questions SET explanation = CASE id
WHEN 409 THEN 'A alternativa D é correta porque o narrador distingue explicitamente duas Eunices — a de antes, ''a rainha da etiqueta, do bom senso, da sobriedade, da educação'', e a de agora, transformada pela doença. A formulação ''Era a falta dela em seu próprio cérebro. Era ela ausente do seu corpo'' evidencia uma cisão entre a identidade construída ao longo da vida e a pessoa que a doença produz. A é incorreta porque descreve apenas a perda, sem captar a ideia de cisão entre duas identidades coexistentes. B é incorreta porque o texto não sugere que a agressividade revele traços reprimidos. C é incorreta porque a recusa não é deliberada — é efeito da doença, não de uma escolha.'
WHEN 410 THEN 'A expressão ''remontar dos cacos'' é uma metáfora que evoca a reconstrução a partir de fragmentos, como quem recompõe um objeto quebrado usando os pedaços disponíveis.

A alternativa A é correta porque a expressão indica que Eunice se reconstrói aproveitando os fragmentos de experiências anteriores — filhos crescidos, aposentadoria, bens acumulados —, recompondo-se a partir do que restou de suas fases precedentes. B é incorreta porque não há rejeição da vida pregressa; ao contrário, os ''cacos'' são justamente as conquistas anteriores. C é incorreta porque a metáfora sugere continuidade na reconstrução, não ausência de continuidade. D é incorreta porque Eunice não abandona conquistas profissionais — ela se aposenta tendo cumprido sua missão.'
WHEN 411 THEN 'A alternativa B é correta porque o episódio mostra que, mesmo em estágio avançado de demência, Eunice é capaz de articular uma frase coerente, com ''começo, meio e fim'', demonstrando lampejos de inteligência e senso crítico que persistem apesar da deterioração. O próprio narrador se surpreende com ''aquele segundo de lucidez, em que um raciocínio se formou''. A é incorreta porque, embora a frase tenha conteúdo político, o episódio não se limita à manutenção de opiniões — revela a persistência da capacidade cognitiva. C é incorreta porque não há tentativa consciente de participação; o lampejo é involuntário e surpreendente. D é incorreta porque a frase demonstra compreensão do contexto da conversa, não reprodução mecânica.'
END
WHERE id IN (409, 410, 411);

-- S3 batch (ids 412, 413, 414)
UPDATE questions SET explanation = CASE id
WHEN 412 THEN 'A metáfora é uma figura de linguagem que estabelece uma relação de semelhança implícita entre dois termos, transferindo sentido de um campo semântico para outro sem uso de conectivo comparativo.

A alternativa C é correta porque a referência a ''atos'' organiza a vida de Eunice como uma narrativa dramática com progressão trágica — do primeiro ato (juventude) ao quarto (Alzheimer), descrito como ''o mais injusto, cruel, definitivo''. A palavra ''tragédia'' no próprio trecho confirma que o narrador estrutura a experiência vivida como enredo teatral com desfecho trágico. A é incorreta porque metonímia substituiria a parte pelo todo, o que não ocorre aqui. B é incorreta porque a comparação exigiria um conectivo explícito (como, tal qual). D é incorreta porque o narrador não exagera — o sofrimento descrito é factual e documentado.'
WHEN 413 THEN 'A alternativa D é correta porque a imagem da escada que se desce ''bruscamente de degraus'' representa a deterioração como um movimento descendente e irreversível — cada fase é ''sempre pior que a anterior'' e chega-se ''inexoravelmente'' ao próximo estágio. A direção é para baixo e sem possibilidade de retorno. A é incorreta porque o advérbio ''inexoravelmente'' exclui qualquer possibilidade de retorno. B é incorreta porque a descida é descrita como ''brusca'', não gradual. C é incorreta porque a imagem da escada não atenua o impacto — ao contrário, a descida brusca o intensifica.'
WHEN 414 THEN 'A ironia consiste em dizer algo que, na superfície, apresenta um sentido positivo ou neutro, mas que, pela contradição com o contexto, revela um sentido mais profundo e muitas vezes doloroso.

A alternativa A é correta porque o narrador transforma um sintoma grave — a incapacidade de reconhecer algo já visto — em uma imagem que sugere renovação (''como uma piada nunca contada''), criando ironia ao apresentar a perda de memória como se fosse um ganho de frescor perceptivo. O efeito é simultaneamente terno e cruel. B é incorreta porque o tom do trecho não é de indiferença, mas de observação comovida. C é incorreta porque o foco não é a crítica ao entretenimento, mas o efeito da doença. D é incorreta porque não há compaixão excessiva — o narrador relata com contenção irônica.'
END
WHERE id IN (412, 413, 414);

-- S4 batch (ids 415, 416, 417)
UPDATE questions SET explanation = CASE id
WHEN 415 THEN 'Polifonia é o recurso narrativo em que diferentes vozes, registros ou perspectivas coexistem no texto, enriquecendo a compreensão do fenômeno representado ao confrontar pontos de vista distintos.

A alternativa B é correta porque o narrador justapõe a descrição clínica de Drauzio Varella — objetiva e técnica — com sua própria versão dos estágios, carregada de emoção e experiência vivida (''revolta em todos, não é justo, não é justo''). Esse confronto de registros discursivos distintos sobre o mesmo fenômeno cria um efeito polifônico. A é incorreta porque o narrador não desqualifica o saber científico; ele o complementa. C é incorreta porque o narrador demonstra conhecer a terminologia médica, não ignorá-la. D é incorreta porque o procedimento é literário e subjetivo, não de divulgação científica.'
WHEN 416 THEN 'A anáfora é a repetição de uma palavra ou expressão no início de frases ou segmentos sucessivos, produzindo ênfase e ritmo.

A alternativa C é correta porque a repetição de ''concordar'' três vezes no início de frases sucessivas mimetiza o próprio gesto que descreve — a repetição como estratégia de apaziguamento. Assim como a família repetia a concordância para acalmar Eunice, o texto repete a palavra para que o leitor experimente ritmicamente esse mecanismo. A é incorreta porque o efeito não é de tédio, mas de descoberta de uma solução. B é incorreta porque o registro não é científico, mas experiencial. D é incorreta porque a passagem celebra a eficácia da estratégia, não lamenta a ineficácia de tratamentos.'
WHEN 417 THEN 'A alternativa D é correta porque a frase ''A inteligência tem a capacidade de surpreender e se readaptar a todas as situações'', originalmente dita pelo médico sobre a lucidez residual de Eunice na consulta, é retomada após a descrição da redução de toda sua comunicação ao monossílabo ''é''. Nesse novo contexto, a ''readaptação'' ganha sentido diverso: não é mais a inteligência que surpreende por sua complexidade, mas por sua capacidade de se simplificar ao extremo e ainda assim manter uma presença comunicativa. A é incorreta porque o narrador não contradiz a frase — ele a ressignifica. B é incorreta porque o tom não é de confirmação literal, mas de reinterpretação. C é incorreta porque, embora haja humor compungido, o efeito principal é a ressignificação, não a ironia pura.'
END
WHERE id IN (415, 416, 417);

-- S5 batch (ids 418, 419, 420)
UPDATE questions SET explanation = CASE id
WHEN 418 THEN 'A alternativa A é correta porque a grafia ''por-ca-ri-a'', separando as sílabas com hífens, reproduz visualmente a pronúncia enfática e silabada de Eunice, transformando a representação escrita em registro sonoro da fala da personagem. O recurso captura a entonação irritada e pausada com que ela pronunciava a palavra. B é incorreta porque não se trata de correção de pronúncia, mas de registro expressivo da entonação. C é incorreta porque Eunice não desaprendeu a pronúncia — ela enfatiza cada sílaba deliberadamente. D é incorreta porque a hifenização não indica regionalismo, mas entonação enfática individual.'
WHEN 419 THEN 'A alternativa B é correta porque o monossílabo ''é'', embora represente uma redução extrema da linguagem, ainda constitui uma resposta — uma forma mínima de presença comunicativa que permite o diálogo, mesmo precário. O narrador observa que Eunice ''passou a se comunicar com o mundo por muito tempo'' através dessa única palavra, evidenciando permanência e não ausência total. A é incorreta porque o ''é'' não expressa desinteresse, mas participação mínima. C é incorreta porque a palavra não encerra o diálogo — ao contrário, possibilita a continuidade da interação. D é incorreta porque o ''é'' produz sentido ao funcionar como assentimento, não sendo incapacidade absoluta.'
WHEN 420 THEN 'A alternativa C é correta porque a objeção de Eunice — ''Jesus não era nenhum senhor, era um jovem!'' — questiona a hierarquização implícita no vocativo ''Senhor'', revelando uma postura crítica persistente que sobrevive ao avanço da doença. Ela analisa a linguagem litúrgica e contesta sua adequação, demonstrando senso crítico ativo. A é incorreta porque a objeção não exige erudição teológica, mas sensibilidade linguística. B é incorreta porque a posição de Eunice é justamente o oposto de uma interpretação dogmática — ela questiona a tradição. D é incorreta porque a irritação genuína e a argumentação coerente demonstram compreensão plena do significado.'
END
WHERE id IN (418, 419, 420);

-- S6 batch (ids 421, 422, 423)
UPDATE questions SET explanation = CASE id
WHEN 421 THEN 'A alternativa D é correta porque o narrador sobrepõe camadas de violência no mesmo território: a favela do Pinto foi incendiada em 1969, durante a ditadura, e sobre seus escombros ergueu-se o condomínio Selva de Pedra, habitado por militares. Eunice, viúva de um desaparecido político, passa a morar ali, evidenciando a sobreposição de violência urbana (remoção da favela) e política (ditadura militar) num único espaço geográfico. A é incorreta porque o texto não trata de valor imobiliário, mas de camadas históricas. B é incorreta porque o narrador não sugere indiferença de Eunice, mas registra a ironia da situação. C é incorreta porque, embora a convivência irônica exista, a alternativa D é mais abrangente ao incluir tanto a violência urbana quanto a política.'
WHEN 422 THEN 'A alternativa A é correta porque as perguntas retóricas — ''Depois de tudo o que passou?'', ''Como Deus pode ser tão imprudente?'' — situam o Alzheimer como mais uma injustiça numa sequência de violências: a ditadura, o desaparecimento do marido, os anos de reconstrução, e agora a doença ''justamente agora, quando ia curtir a velhice com dignidade''. O narrador acumula sofrimentos para denunciar a crueldade do destino. B é incorreta porque o texto não apresenta a doença como castigo divino, mas como injustiça. C é incorreta porque o narrador não sugere previsibilidade — ao contrário, expressa revolta diante do inesperado. D é incorreta porque todo o trecho vincula a doença ao contexto biográfico de sofrimentos anteriores.'
WHEN 423 THEN 'A alternativa B é correta porque o alerta médico — ''Cuidado com a indústria de aproveitadores de portadores de demência'' — revela que pacientes com demência são vulneráveis à exploração econômica, uma dimensão social concreta da doença que ultrapassa o aspecto clínico. O próprio episódio das duas televisões compradas sem necessidade já ilustra essa vulnerabilidade. A é incorreta porque o alerta demonstra justamente a relevância do tema financeiro. C é incorreta porque o alerta não gera desconfiança generalizada, mas atenção específica a aproveitadores. D é incorreta porque a crítica não é ao sistema de saúde, mas a indivíduos que exploram a fragilidade dos pacientes.'
END
WHERE id IN (421, 422, 423);

-- S7 batch (ids 424, 425, 426)
UPDATE questions SET explanation = CASE id
WHEN 424 THEN 'A alternativa C é correta porque o narrador constrói uma argumentação que dissocia a doença da pessoa: ''Não era mamãe me xingando'', ''Era a doença que gritava'', ''Era a doença que agia e a mobilizava''. Essa dissociação funciona como estratégia de sobrevivência emocional — ao separar a mãe da doença, a família consegue ''não levar as ofensas para o lado pessoal'' e manter a convivência com a paciente. A é incorreta porque, embora preservar a imagem da mãe seja um efeito, o objetivo central é viabilizar a convivência. B é incorreta porque o narrador não nega a agressividade — ele a reconhece e a atribui à doença. D é incorreta porque o narrador não culpabiliza os familiares; ao contrário, os apresenta como vítimas dos efeitos da doença.'
WHEN 425 THEN 'A alternativa D é correta porque o narrador explicita que a família preferiu manter Eunice consigo, contrariando a recomendação de ''advogados e médicos'', e justifica essa escolha pelo desejo de ''tornar sua rotina agradável e feliz''. A decisão valoriza o vínculo afetivo como forma de resistir à desumanização imposta pela doença, mantendo Eunice inserida no convívio familiar em vez de entregá-la a uma instituição. A é incorreta porque o texto não expressa desconfiança em relação às instituições de saúde. B é incorreta porque não há menção a motivação religiosa. C é incorreta porque, embora se aproxime da resposta correta, não capta a dimensão de resistência à desumanização que a alternativa D expressa.'
WHEN 426 THEN 'A distinção entre memória episódica (eventos vividos) e memória cultural (referências compartilhadas, como filmes e expressões) é relevante para compreender como o Alzheimer afeta diferentes sistemas de memória de formas distintas.

A alternativa A é incorreta porque a escolha correta é D. A alternativa D é correta porque o apelido ''Meu Homem de Preto'' não demonstra lucidez plena nem memória episódica preservada, mas exemplifica como a doença pode produzir associações criativas involuntárias — a conexão entre o terno preto do segurança e o filme Men in Black surge como um lampejo associativo espontâneo, não como raciocínio deliberado. B é incorreta porque, embora toque na persistência da memória cultural, o texto enfatiza o caráter criativo e involuntário da associação. C é incorreta porque o narrador deixa claro que Eunice estava em estágio avançado da doença.'
END
WHERE id IN (424, 425, 426);

-- S8 batch (ids 427, 428, 429)
UPDATE questions SET explanation = CASE id
WHEN 427 THEN 'A intertextualidade ocorre quando um texto estabelece relação explícita com outro, incorporando citações, alusões ou referências que enriquecem o sentido da obra.

A alternativa B é correta porque o narrador cita Fitzgerald — ''não há segundo ato na vida dos americanos'' — para imediatamente contrapor essa sentença à vida de Eunice, que já estava no ''quarto ato''. A ironia reside no contraste: enquanto Fitzgerald nega a possibilidade de reinvenção, Eunice se reinventou múltiplas vezes, tornando sua trajetória excepcional em relação à máxima do escritor. A é incorreta porque a tese de Fitzgerald é justamente contradita pela experiência de Eunice. C é incorreta porque não há comparação com personagens ficcionais de Fitzgerald. D é incorreta porque a citação não funciona como argumento de autoridade — ela é subvertida.'
WHEN 428 THEN 'A alternativa C é correta porque, ao reter o exemplar de Feliz ano velho em alemão entre mais de cinco mil livros, Eunice preserva inconscientemente o vínculo com o filho autor, mesmo quando a doença já compromete sua capacidade de escolha racional. O livro do filho sobrevive ao descarte massivo, sugerindo que o vínculo materno persiste para além da deterioração cognitiva. A é incorreta porque reter o livro do filho indica o oposto de indiferença. B é incorreta porque o texto não sugere curiosidade pelo objeto, mas vínculo afetivo. D é incorreta porque Eunice não dominava alemão — o livro representa o filho, não a língua.'
WHEN 429 THEN 'A alternativa C é correta porque a sequência ''vou morar aqui, envelhecer aqui, morrer aqui'' condensa em uma única frase todo o percurso que o capítulo narrará em detalhes — a instalação no Leblon, o envelhecimento com Alzheimer e a progressiva deterioração rumo à dependência total. O capítulo desenvolve exatamente essa trajetória antecipada pela frase. A é incorreta porque o tom não é de resignação, mas de determinação e autonomia. B é incorreta porque, embora haja ironia trágica retrospectiva, a frase funciona estruturalmente como antecipação do percurso narrativo. D é incorreta porque a decisão é apresentada como planejada e firme, não impulsiva.'
END
WHERE id IN (427, 428, 429);

-- S9 batch (ids 430, 431, 432)
UPDATE questions SET explanation = CASE id
WHEN 430 THEN 'A alternativa A é correta porque o vizinho, ao chamar a doença de ''o alemão'' em vez de ''Alzheimer'', reproduz no ato de nomear o mesmo mecanismo de esquecimento que a doença provoca — ele designa a enfermidade sem pronunciar seu nome, assim como o Alzheimer apaga nomes e palavras da memória. O título do capítulo, ''O alemão impronunciável'', reforça essa ideia: a palavra que não se consegue dizer espelha as palavras que a doença faz desaparecer. B é incorreta porque o gesto não é de homenagem, mas de recusa bem-humorada do nome técnico. C é incorreta porque a dificuldade não é técnica ou fonética, mas afetiva e simbólica. D é incorreta porque não há sugestão de origem genética europeia.'
WHEN 431 THEN 'A alternativa B é incorreta; a correta é A. A organização do capítulo pelos estágios da doença substitui a cronologia biográfica convencional por uma progressão clínica — Estágio I, II, III, IV — que mimetiza a própria deterioração de Eunice. A estrutura narrativa acompanha o declínio da personagem, fazendo com que a forma do texto reproduza seu conteúdo. B é incorreta porque o narrador não busca rigor científico — ele subverte a classificação médica com sua experiência pessoal. C é incorreta porque a organização por estágios é sistemática, não aleatória. D é incorreta porque o objetivo não é didático, mas narrativo e expressivo.'
WHEN 432 THEN 'A alternativa C é correta porque a sequência de três verbos em progressão — ''morar'', ''envelhecer'', ''morrer'' — antecipa de forma condensada o percurso que o capítulo inteiro desenvolverá: a instalação no apartamento, o avanço do Alzheimer durante o envelhecimento e a caminhada rumo à dependência total. A frase funciona como síntese prospectiva de toda a narrativa do capítulo. A é incorreta porque o tom é de determinação e autonomia, não de resignação. B é incorreta porque, embora a ironia trágica exista retrospectivamente, a função principal da frase é estrutural — antecipar o percurso. D é incorreta porque a frase expressa planejamento firme, não impulsividade.'
END
WHERE id IN (430, 431, 432);
