-- Batch 1: S1 (IDs 298, 299, 300)
UPDATE questions SET explanation = CASE id
WHEN 298 THEN 'O capítulo 12 narra a reconstrução da vida de Eunice e dos filhos após os anos mais sombrios do luto, mostrando como ela se reinventou profissionalmente e reergueu a estrutura familiar a partir de um novo modelo materno.

A alternativa C é correta porque o trecho ''Nascia uma nova Eunice. Renascia uma família'' sintetiza dois movimentos simultâneos: a transformação pessoal da mãe e, como consequência direta, a reorganização do núcleo familiar — o verbo ''renascia'' indica que a família se reconstitui a partir da figura materna reinventada. A é incorreta porque o texto não apresenta a superação como definitiva nem a reduz à independência financeira. B é incorreta porque Eunice não substitui a identidade de esposa, mas a amplia com novas funções sem abandonar a memória do marido. D é incorreta porque a normalidade não é recuperada e o fim do regime militar não é mencionado como causa dessa transformação.'
WHEN 299 THEN 'A alternativa A é correta porque a frase ''Você é o único homem da casa'' reaparece em diferentes momentos do capítulo — na festa, no vestibular, na pensão — sempre reforçando o peso de uma responsabilidade que recai sobre o narrador ainda jovem, em decorrência direta da ausência do pai desaparecido. A repetição funciona como refrão que evidencia a carga prematura imposta ao filho. B é incorreta porque a mãe não reproduz valores patriarcais de forma consciente ou ideológica, mas reage à situação concreta do desaparecimento. C é incorreta porque não há pressão para que ele seja provedor financeiro, mas sim responsável moral pela família. D é incorreta porque o narrador não expressa ressentimento, mas compreensão e até cumplicidade com a expectativa materna.'
WHEN 300 THEN 'A alternativa D é correta porque o trecho descreve Eunice chorando ''trancada no escuro'' todas as noites para que os filhos não percebessem, indicando que ela sacrificava deliberadamente o próprio bem-estar emocional — ''não queria que percebêssemos, mas que tivéssemos uma infância e adolescência sem âncoras na alma''. O objetivo explícito é proteger os filhos. A é incorreta porque não se trata de disfarce pragmático, mas de escolha consciente de ocultação do sofrimento em favor dos filhos. B é incorreta porque Eunice não demonstra impossibilidade de conciliar luto e exigências sociais, mas opta ativamente por essa separação. C é incorreta porque a solidão não é consequência de uma escolha genérica, mas instrumento deliberado de proteção materna.'
END WHERE id IN (298, 299, 300);

-- Batch 2: S2 (IDs 301, 302, 303)
UPDATE questions SET explanation = CASE id
WHEN 301 THEN 'A alternativa B é correta porque a sequência de ações — trabalhar pela primeira vez, aprender o básico, fazer vestibular, formar-se em direito — desenha uma trajetória ascendente em que Eunice transforma a adversidade do desaparecimento do marido em motor de reinvenção pessoal e intelectual. O texto enfatiza que ela partiu do zero (''Era a primeira vez que trabalhava'') e construiu uma nova identidade. A é incorreta porque o texto não apresenta a trajetória como compensação pela ausência do marido nem como busca de ascensão social. C é incorreta porque a independência de Eunice não é apresentada como típica de sua geração, mas como resposta singular a uma situação extrema. D é incorreta porque não há menção a pressões familiares externas — a iniciativa parte da própria Eunice.'
WHEN 302 THEN 'O conceito de gauche, na tradição drummondiana, designa o sujeito deslocado, que caminha à margem das convenções e aceita sua inadequação como marca identitária.

A alternativa D é correta porque o narrador não rejeita completamente o legado paterno — tenta a engenharia civil como o pai, busca tirar brevê — mas acaba conciliando o peso dessa herança com a descoberta de uma vocação própria nas artes, sintetizada na voz que diz ''Vai, Marcelo, ser gauche na vida''. A é incorreta porque ele não rejeita conscientemente o legado paterno, mas hesita longamente antes de se afastar dele. B é incorreta porque ele não escolhe engenharia por prestígio, mas por senso de obrigação familiar. C é incorreta porque o conflito se resolve quando ele finalmente muda para Comunicações e Artes.'
WHEN 303 THEN 'A alternativa A é correta porque os verbos ''tocar'' e ''seguir'' não significam esquecer nem superar: eles indicam continuidade sem encerramento, uma postura que recusa tanto a negação da perda quanto a pretensão de superá-la. Eunice segue vivendo sem fingir que a dor acabou, como confirmam as cenas de choro noturno descritas no mesmo trecho. B é incorreta porque Eunice não demonstra resignação diante da injustiça — ela busca reconhecimento jurídico ao longo do capítulo. C é incorreta porque o trecho não apresenta a ação prática como fuga do enfrentamento emocional, já que ela chora todas as noites. D é incorreta porque não há indiferença afetiva — o texto mostra uma dor intensa que Eunice apenas oculta dos filhos.'
END WHERE id IN (301, 302, 303);

-- Batch 3: S3 (IDs 304, 305, 306)
UPDATE questions SET explanation = CASE id
WHEN 304 THEN 'Ironia é a figura de linguagem que estabelece uma incongruência entre o que se diz ou acontece e o que seria esperado, produzindo um efeito de estranhamento ou humor.

A alternativa D é correta porque a ironia reside na coincidência entre a nacionalidade do embaixador cujo sequestro provocou a mudança da família (o embaixador suíço Giovanni Bucher) e o tipo de restaurante em que a casa se transformou (um restaurante suíço). O próprio narrador sinaliza a ironia ao dizer ''Que ironia''. A é incorreta porque a ironia não se baseia na contradição entre destino da casa e expectativas da família, mas na coincidência do elemento ''suíço''. B é incorreta porque o texto não opõe alegria do restaurante a tristeza das memórias. C é incorreta porque a ironia não decorre de semelhança fonética, mas de coincidência factual.'
WHEN 305 THEN 'Metáfora é a figura de linguagem que estabelece uma relação de semelhança implícita entre dois termos de campos semânticos distintos, transferindo o sentido de um para o outro.

A alternativa C é correta porque a fogueira e o facho de luz representam metaforicamente um novo ponto de referência, uma orientação que permita a Eunice encontrar ''a volta para a costa, para a terra firme, o chão'' — ou seja, um novo sentido de direção após a perda do marido, que era a referência central da família. A é incorreta porque o trecho não contém elementos religiosos nem menção a milagres. B é incorreta porque a metáfora se projeta para o futuro (''esperar reacenderem''), não para o passado. D é incorreta porque a metáfora não se refere a liderança política, mas a orientação existencial e familiar.'
WHEN 306 THEN 'Intertextualidade é o recurso que consiste na incorporação de um texto alheio — por citação, paráfrase ou alusão — dentro de um novo contexto, alterando ou ampliando seu sentido original.

A alternativa B é correta porque o narrador se apropria do verso de Drummond (''Vai, Carlos, ser gauche na vida''), substituindo ''Carlos'' por ''Marcelo'', e transforma o sentimento de inadequação original do poema em aceitação da própria vocação artística ao abandonar a engenharia. A apropriação é irônica porque converte o desajuste em libertação. A é incorreta porque o objetivo não é demonstrar erudição, mas expressar um momento de decisão pessoal. C é incorreta porque o verso não funciona como homenagem ao poeta, mas como instrumento de autocompreensão. D é incorreta porque o tom não é de lamento, mas de aceitação e até alívio.'
END WHERE id IN (304, 305, 306);

-- Batch 4: S4 (IDs 307, 308, 309)
UPDATE questions SET explanation = CASE id
WHEN 307 THEN 'Leitmotiv é um recurso narrativo em que uma frase, imagem ou tema reaparece ao longo do texto com variações de contexto, funcionando como fio condutor que estrutura a narrativa e acumula significado a cada repetição.

A alternativa A é correta porque a frase ''Você é o único homem da casa'' reaparece em contextos distintos — a festa, o vestibular, a pensão, a escolha de carreira — transformando a voz da mãe em um leitmotiv que marca a passagem do tempo e organiza cronologicamente a formação do narrador. B é incorreta porque a repetição não é mecânica nem acrítica; o narrador reflete sobre ela em diferentes momentos. C é incorreta porque o narrador não obedece irrestritamente — ele acaba abandonando a engenharia. D é incorreta porque a repetição não fragmenta a narrativa, mas a unifica em torno de um eixo temático.'
WHEN 308 THEN 'A alternativa B é correta porque a cena em que o narrador revisita a casa transformada em restaurante suíço justapõe passado e presente no mesmo espaço físico: ele circula pelos quartos reconhecendo pisos, treliças e fechaduras inalterados, enquanto o quarto se transformara num ''depósito de garrafas''. Essa sobreposição temporal evidencia a passagem do tempo e a perda. A é incorreta porque a cena não cria uma moldura ficcional, mas um confronto direto entre memória e realidade presente. C é incorreta porque o tom da cena é melancólico e nostálgico, não cômico. D é incorreta porque o foco não está nas transformações urbanas do bairro, mas na experiência íntima do narrador diante do espaço familiar alterado.'
WHEN 309 THEN 'Anáfora é a repetição de uma mesma estrutura sintática no início de frases ou períodos consecutivos, criando ritmo e ênfase.

A alternativa C é correta porque a repetição de ''Meses sem ter um endereço fixo. Meses improvisando uma vida. Meses sem responsabilidades!'' contrasta diretamente com o refrão ''Você é o único homem da casa [...] Tem que cuidar delas'' que atravessa o capítulo. A exclamação final (''Meses sem responsabilidades!'') marca a liberdade como contraponto ao peso das obrigações familiares. A é incorreta porque o trecho não denuncia precariedade, mas celebra a liberdade. B é incorreta porque o ritmo não é de urgência, mas de expansão e alívio. D é incorreta porque o tom não é nostálgico, mas de constatação presente do contraste entre liberdade e dever.'
END WHERE id IN (307, 308, 309);

-- Batch 5: S5 (IDs 310, 311, 312)
UPDATE questions SET explanation = CASE id
WHEN 310 THEN 'O infinitivo impessoal, quando usado isoladamente em frases nominais, adquire valor imperativo ou sentencioso, conferindo às palavras um caráter de ordem, determinação ou princípio de conduta.

A alternativa D é correta porque os infinitivos ''Tocar. Seguir.'', colocados após as perguntas retóricas que descartam superar e esquecer, funcionam como imperativos que traduzem a determinação de Eunice em continuar vivendo apesar da dor. A pontuação em frases mínimas reforça o caráter resoluto e inapelável da decisão. A é incorreta porque o efeito não é de simplificação, mas de intensificação — a brevidade confere força, não objetividade pragmática. B é incorreta porque o trecho não reproduz angústia existencial, mas decisão firme. C é incorreta porque os infinitivos não sugerem fragmentação emocional, mas coesão de propósito.'
WHEN 311 THEN 'A alternativa C é correta porque a repetição de ''estresse metafísico'' sete vezes, aplicada a situações cada vez mais triviais (insônia, fumar, beber, xingar a TV), cria um efeito cômico que ironiza a pretensão intelectual do narrador adolescente que se declarava existencialista. O exagero deliberado revela autoconsciência humorística. A é incorreta porque a repetição não confere seriedade, mas a mina pelo excesso. B é incorreta porque o trecho não trata da ausência paterna, mas da autodefinição filosófica do narrador. D é incorreta porque o narrador não reproduz um estilo argumentativo filosófico, mas parodia sua própria pose intelectual juvenil.'
WHEN 312 THEN 'Paradoxo é a figura de linguagem que reúne ideias aparentemente contraditórias numa mesma formulação, revelando uma verdade mais profunda ou uma situação absurda.

A alternativa A é correta porque a expressão ''ele não estava morto nem vivo'' constitui um paradoxo que traduz a situação kafkiana de um desaparecido político sem atestado de óbito: juridicamente, Rubens Paiva não podia ser declarado morto nem tratado como vivo, o que bloqueava todas as ações financeiras da família. O termo ''aberração jurídica'' no próprio texto reforça o caráter absurdo. B é incorreta porque não há atenuação — o texto expõe cruamente a brutalidade burocrática. C é incorreta porque não se trata de exagero, mas de descrição literal da situação jurídica. D é incorreta porque a antítese opõe termos contrários sem contradição lógica, enquanto o paradoxo aqui reside na coexistência impossível das duas condições.'
END WHERE id IN (310, 311, 312);

-- Batch 6: S6 (IDs 313, 314, 315)
UPDATE questions SET explanation = CASE id
WHEN 313 THEN 'A alternativa B é correta porque o trecho descreve ''velhinhas religiosas da ala católica'' organizadas por ''dom Paulo Evaristo Arns'' participando ao lado dos estudantes nas manifestações, evidenciando a convergência entre setores religiosos e estudantis na resistência ao regime. O Movimento Contra a Carestia unia diferentes grupos sociais sob uma mesma bandeira de oposição. A é incorreta porque o trecho mostra justamente o oposto — a união, e não a fragmentação, dos movimentos de oposição. C é incorreta porque o texto menciona religiosas e estudantes, não a predominância de uma classe específica. D é incorreta porque o texto não avalia a eficácia das manifestações, mas descreve a composição plural da resistência.'
WHEN 314 THEN 'O conceito de violência estrutural refere-se à forma como sistemas jurídicos e institucionais podem prolongar e amplificar os efeitos de uma violência originalmente física, atingindo dimensões econômicas, sociais e psicológicas.

A alternativa A é correta porque a enumeração — não poder sacar dinheiro, não resgatar seguro de vida, não requerer pensão — demonstra como o desaparecimento forçado prolongava a violência do Estado para além da esfera física, atingindo a sobrevivência financeira da família. A impossibilidade jurídica decorria diretamente da ação repressiva que eliminou Rubens Paiva sem registrar sua morte. B é incorreta porque os fatos descritos ocorrem durante a ditadura, não após a redemocratização. C é incorreta porque o problema não é a dependência feminina genérica, mas a situação específica criada pelo desaparecimento forçado. D é incorreta porque não se trata de omissão do judiciário, mas de uma lacuna jurídica imposta pela ausência de atestado de óbito.'
WHEN 315 THEN 'A alternativa D é correta porque o narrador justapõe deliberadamente ''Ano em que prestei o primeiro vestibular'' e ''Ano em que recomeçaram as manifestações políticas no Brasil'', entrelaçando sua trajetória individual com o processo histórico coletivo da abertura política. A construção paralela indica que a biografia pessoal e a história do país se desenvolvem de forma imbricada, não separada. A é incorreta porque o texto mostra compatibilidade, não incompatibilidade, entre vida estudantil e engajamento. B é incorreta porque a influência da história familiar na consciência política não é o foco deste trecho específico. C é incorreta porque o narrador não apresenta a justaposição como coincidência fortuita, mas como entrelaçamento significativo.'
END WHERE id IN (313, 314, 315);

-- Batch 7: S7 (IDs 316, 317, 318)
UPDATE questions SET explanation = CASE id
WHEN 316 THEN 'A alternativa C é correta porque o narrador observa como ''a divisão de classes cria rituais próprios'' — ele ficava no ponto de carona dos estudantes enquanto o pedreiro ia ''resignado para o seu busão, sua condução, o transporte dos trabalhadores''. A reflexão expõe como hábitos cotidianos aparentemente banais (o ponto de carona versus o ponto de ônibus) reproduzem e naturalizam desigualdades estruturais. A é incorreta porque a observação não se restringe à universidade, mas à dinâmica social mais ampla. B é incorreta porque o narrador não faz uma autocrítica explícita sobre condescendência, mas uma observação sobre a mecânica da separação de classes. D é incorreta porque o narrador não defende a convivência entre classes como solução transformadora — ele constata a distância.'
WHEN 317 THEN 'A alternativa D é correta porque o narrador analisa retrospectivamente suas próprias motivações ao escolher engenharia: reconhece que ''deduzia'' que a mãe o preferia engenheiro, que queria ''ajudar nas finanças abaladas da família'' e que sentia a pressão de ser ''o único homem da casa''. Essa autoanálise identifica a culpa e o dever como forças constitutivas de sua identidade, sem absolver nem condenar ninguém. A é incorreta porque o narrador não busca absolver a mãe — ele reconhece que a pressão era também interna. B é incorreta porque o tom não é confessional nem expõe fraqueza de caráter, mas complexidade de motivações. C é incorreta porque o narrador não generaliza sua experiência para representar uma geração inteira.'
WHEN 318 THEN 'Autodepreciação irônica é um recurso retórico em que o narrador diminui deliberadamente a importância de suas próprias ações para produzir humor e relativizar seu papel nos acontecimentos.

A alternativa A é correta porque o narrador descreve o gesto de chutar uma bomba de volta aos policiais como ''minha grande contribuição para combater a ditadura'', usando a grandiloquência da expressão para ironizar a modéstia real do ato. O humor nasce do contraste entre a magnitude sugerida e a trivialidade do gesto. B é incorreta porque o exagero não visa engrandecer a ação, mas justamente relativizá-la. C é incorreta porque o narrador não critica as manifestações, mas ri de si mesmo. D é incorreta porque o tom irônico exclui a leitura de reconhecimento sincero.'
END WHERE id IN (316, 317, 318);

-- Batch 8: S8 (IDs 319, 320, 321)
UPDATE questions SET explanation = CASE id
WHEN 319 THEN 'O verso ''Vai, Carlos, ser gauche na vida'', do ''Poema de sete faces'' de Carlos Drummond de Andrade, expressa a aceitação de um destino marcado pelo deslocamento e pela inadequação em relação às normas convencionais.

A alternativa B é correta porque o narrador substitui ''Carlos'' por ''Marcelo'' e usa o verso no momento em que desiste da engenharia agrícola para seguir as artes, expressando a aceitação do próprio destino como alguém que não se encaixa nas expectativas convencionais de carreira e sucesso financeiro. A é incorreta porque o objetivo não é demonstrar influência literária, mas traduzir uma decisão existencial. C é incorreta porque o verso não funciona como homenagem ao poeta, mas como instrumento de identificação pessoal. D é incorreta porque o tom não é de ironia contra si mesmo como ex-estudante de engenharia, mas de aceitação libertadora.'
WHEN 320 THEN 'A alternativa C é correta porque comparar Heráclito a uma ''droga mais pesada'' e mencionar que os livros de cálculo e resistência dos materiais ''mofavam'' constrói com humor o retrato de um estudante de engenharia seduzido pela filosofia em detrimento da formação técnica. O contraste entre a intensidade das discussões filosóficas noturnas e o abandono dos manuais de engenharia é deliberadamente cômico. A é incorreta porque o trecho não denuncia precariedade do ensino, mas retrata a escolha pessoal do narrador. B é incorreta porque não há hierarquização entre filosofia e ciências exatas, mas relato humorístico de uma preferência. D é incorreta porque o trecho não trata de alienação política, mas de vocação intelectual.'
WHEN 321 THEN 'A alternativa A é correta porque a referência a Hobbes (''O homem é o lobo do homem'') é aplicada ao contexto de uma festa de adolescentes que saiu do controle — com ''guerra de extintor de incêndio'', mergulhos na piscina e maconha —, criando um efeito cômico pela desproporção entre a gravidade da citação filosófica sobre o estado de natureza e a banalidade da situação doméstica. O próprio narrador sinaliza o humor ao chamar a carta de ''obra-prima literária''. B é incorreta porque o contexto não é de formação intelectual precoce, mas de autocrítica humorística. C é incorreta porque, embora haja paralelo possível entre caos da festa e estado de natureza, o efeito dominante é o cômico, não o analítico. D é incorreta porque não há crítica aos vizinhos, mas autoironia do narrador.'
END WHERE id IN (319, 320, 321);

-- Batch 9: S9 (IDs 322, 323, 324)
UPDATE questions SET explanation = CASE id
WHEN 322 THEN 'A alternativa D é correta porque o título ''Depois do luto'' sinaliza a passagem de um tempo dominado pela tragédia — o desaparecimento de Rubens Paiva e suas consequências — para outro orientado pela reconstrução da vida familiar. Ao abrir a Parte 3 com este título, a obra marca estruturalmente a transição temática. A é incorreta porque o advérbio ''depois'' não indica superação definitiva da perda, mas deslocamento temporal. B é incorreta porque não há mudança de gênero — o texto permanece memorialístico e autobiográfico. C é incorreta porque, embora exista contraste com ''O sacrifício'', a função principal do título é sinalizar a nova fase, não apenas contrastar com o capítulo anterior.'
WHEN 323 THEN 'A alternativa B é correta porque o capítulo é composto por episódios aparentemente avulsos — a festa no prédio, o filósofo no carrão, a dona da pensão incendiária, a garota de unhas negras — que, embora pareçam desconexos, dialogam com o tema central da formação do narrador entre obrigação e vocação. A anedota do filósofo no carro importado, por exemplo, ecoa o desejo reprimido de seguir filosofia. A é incorreta porque a estrutura não mimetiza dispersão aleatória da memória, mas organiza episódios em torno de um eixo temático. C é incorreta porque o estilo não é jornalístico, mas memorialístico e literário. D é incorreta porque os episódios não são desconectados do tema — todos se relacionam com a tensão entre dever e desejo.'
WHEN 324 THEN 'A alternativa C é correta porque a repetição de ''Então'' — ''Então mudei para Rádio & TV. Então passei a escrever livros. Então fiz teatro. Então minha mãe não tinha expectativa nenhuma sobre mim'' — sintetiza em progressão acelerada a resolução do conflito entre obrigação familiar e vocação artística que percorre todo o capítulo. A sequência mostra o narrador finalmente livre para seguir seu caminho, culminando na aceitação da mãe. A é incorreta porque o trecho não demonstra falta de direção, mas multiplicidade de caminhos que convergem para as artes. B é incorreta porque o foco não está no ritmo das transformações dos anos 1980, mas na resolução de um conflito pessoal. D é incorreta porque a passagem para a vida adulta independente não é o tema central — o que se resolve é o conflito vocacional.'
END WHERE id IN (322, 323, 324);
